
color = input("Enter a color: ")
social_media = input("Enter a social_media: ")
country = input("Enter a country: ")
plural_noun = input("Enter a Plural Noun: ")
place = input("Enter a Place: ")
state = input("Enter a state: ")
movie_celebrity = input("Enter a movie_celebrity: ")
music_celebrity = input("Enter a music_celebrity: ")
comedy_celebrity = input("Enter a comedy_celebrity: ")

print("Roses are " + color)
print(social_media + " are apps")
print("I love " + country)
print("I like " + plural_noun)
print(plural_noun + " are beautiful")
print("I love " + state)
print("I love " + movie_celebrity)
print(plural_noun + " are good")
print("I love " + music_celebrity)
print("I like " + comedy_celebrity)
